### ISSUE TITLE
Cannot login

### ISSUE THREAD

**Issue by niichapats** [OmegaOoh/ku-tangtee#266]
**Describe the bug**
I have already logged in using my KU account, but it still asks me to log in.

**To Reproduce**
1. Go to home page
2. Click on login
3. Log in using a KU account.
4. After logging in, the message "Please login. Profile creation is needed for the user to be authenticated" still appears.

**Expected behavior**
Should be redirected to an authenticated page after logging in.

**Screenshots**
<img width="1470" alt="Screenshot 2567-11-25 at 13 06 35" src="https://github.com/user-attachments/assets/daa60741-66e6-415d-b824-ec1085e70424">

**Desktop (please complete the following information):**
 - OS: IOS
 - Browser: safari
 - Version: 16.5

**Comment by opxz7148** [comment]
Mac user here. Because of safari/Apple security it's cause our app won't work properly. To make our web work properly you can go to toolbar on the top then go to Safari > Settings > Privacy > Unchecked Prevent cross-site tracking. This will make our website work properly. But if you're uncomfortable to do that you may need to use other browser such as Chrome, Firefox instead. Sorry for inconvenience.
